# Generated by Django 4.2.7 on 2025-12-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('source_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True, null=True)),
                ('detail_link', models.CharField(blank=True, max_length=500, null=True)),
                ('region_sido', models.CharField(blank=True, max_length=50, null=True)),
                ('region_sigungu', models.CharField(blank=True, max_length=50, null=True)),
                ('region_code', models.CharField(blank=True, max_length=20, null=True)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('employment_requirements', models.JSONField(blank=True, default=list)),
                ('education_requirements', models.JSONField(blank=True, default=list)),
                ('major_requirements', models.JSONField(blank=True, default=list)),
                ('income_requirements', models.JSONField(blank=True, default=list)),
                ('special_target', models.JSONField(blank=True, default=list)),
                ('provider', models.CharField(blank=True, max_length=200, null=True)),
                ('apply_method', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('raw', models.JSONField()),
            ],
        ),
    ]
