# Generated by Django 4.2.7 on 2025-12-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('YOUTH', '온통청년'), ('WELFARE', '복지로'), ('WORKNET', '워크넷')], max_length=20)),
                ('category', models.CharField(choices=[('JOB', '일자리'), ('EDU', '교육/훈련'), ('HOUSING', '주거'), ('WELFARE', '복지'), ('FINANCE', '금융'), ('ETC', '기타')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('application_start', models.DateField(blank=True, null=True)),
                ('application_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WelfarePolicyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(blank=True, max_length=100)),
                ('benefit_amount', models.CharField(blank=True, max_length=100)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='welfare_detail', to='policies.policy')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPolicyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('training_field', models.CharField(blank=True, max_length=255)),
                ('certificate', models.CharField(blank=True, max_length=255)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_detail', to='policies.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido_code', models.CharField(max_length=10)),
                ('sigungu_code', models.CharField(blank=True, max_length=10)),
                ('sido_name', models.CharField(max_length=50)),
                ('sigungu_name', models.CharField(blank=True, max_length=50)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='policies.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('employment_status', models.CharField(blank=True, help_text='미취업, 재직, 구직중, 자영업 등', max_length=50)),
                ('education_level', models.CharField(blank=True, help_text='고졸, 대재, 대졸, 대학원 등', max_length=50)),
                ('income_min', models.PositiveIntegerField(blank=True, null=True)),
                ('income_max', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_business_registration', models.BooleanField(blank=True, help_text='사업자등록 필요 여부', null=True)),
                ('special_target', models.CharField(blank=True, help_text='장애인, 보훈대상자, 차상위 등', max_length=100)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='policies.policy')),
            ],
        ),
    ]
