# Generated by Django 4.2.7 on 2025-12-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='applicable_regions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='policy',
            name='apply_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='benefit_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='benefit_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='policy',
            name='employment_status',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='policy',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='policy',
            name='major',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(blank=True, choices=[('YOUTH', '청년정책'), ('WELFARE', '복지서비스')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='region_scope',
            field=models.CharField(choices=[('NATIONWIDE', '전국'), ('LOCAL', '지역')], default='NATIONWIDE', max_length=20),
        ),
        migrations.AddField(
            model_name='policy',
            name='search_summary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='source_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='policy',
            unique_together={('source', 'source_id')},
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_type'], name='policies_po_policy__de1313_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['category'], name='policies_po_categor_8341ff_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['region_sido'], name='policies_po_region__b9585f_idx'),
        ),
        migrations.RemoveField(
            model_name='policy',
            name='detail_link',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='education_requirements',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='employment_requirements',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='income_requirements',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='major_requirements',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='region_code',
        ),
    ]
