# Generated by Django 4.2.7 on 2025-12-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_rename_education_requirements_policy_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='apply_links',
            new_name='detail_links',
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='employment_status',
            new_name='employment',
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='benefit_detail',
            new_name='policy_detail',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='benefit_type',
        ),
        migrations.AddField(
            model_name='policy',
            name='detail_contact',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='policy',
            name='target_detail',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='policy',
            name='apply_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
