# Generated by Django 4.2.7 on 2025-12-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_rename_apply_links_policy_detail_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='search_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
