# Generated by Django 4.2.7 on 2025-12-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_alter_policy_search_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('YOUTH', '청년정책'), ('WELFARE', '복지서비스')], default='YOUTH', max_length=30),
            preserve_default=False,
        ),
    ]
