# Generated by Django 4.2.7 on 2025-12-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_policy_service_type_alter_policy_policy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='applicable_regions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(blank=True, choices=[('YOUTH', '청년정책'), ('WELFARE', '복지서비스')], max_length=30, null=True),
        ),
    ]
